sudo: required
dist: trusty

language: python
python:
   - "2.7"
install: 
   - pip install SQLAlchemy
   - pip install psycopg2
   - pip install paste
   - pip install PasteDeploy
   - pip install Routes
   - pip install webob
services:
    - docker
script:
-  cd wsgi && ./run.sh
